require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 2.5

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 24
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - 'spec/**/*'

Metrics/CollectionLiteralLength:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/RaiseArgs:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/ModuleFunction:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DirEmpty:
  Enabled: true

Style/FileEmpty:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantLineContinuation:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/RescueException:
  Enabled: true
  Exclude:
    - 'lib/health_monitor/providers/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/EmptyClass:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/DuplicateMatchPattern:
  Enabled: true

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/UselessRescue:
  Enabled: true

Lint/MixedCaseRange:
  Enabled: true

Lint/RedundantRegexpQuantifiers:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/EmptyHeredoc:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OperatorMethodCall:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/ExactRegexpMatch:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/RedundantCurrentDirectoryInPath:
  Enabled: true

Style/RedundantFilterChain:
  Enabled: true

Style/RedundantRegexpArgument:
  Enabled: true

Style/RedundantRegexpConstructor:
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/YAMLFileRead:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/BeEq:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/ChangeByZero:
  Enabled: true

RSpec/ClassCheck:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/NoExpectationExample:
  Enabled: true

RSpec/SortMetadata:
  Enabled: true

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true

RSpec/ExpectInLet:
  Enabled: false

RSpec/Rails/AvoidSetupHook:
  Enabled: true

RSpec/Rails/HaveHttpStatus:
  Enabled: true

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/DuplicatedMetadata:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: true

RSpec/RedundantAround:
  Enabled: true

RSpec/SkipBlockInsideExample:
  Enabled: true

RSpec/Rails/MinitestAssertions:
  Enabled: true

RSpec/Rails/TravelAround:
  Enabled: true

RSpec/BeEmpty:
  Enabled: true

RSpec/ContainExactly:
  Enabled: true

RSpec/EmptyMetadata:
  Enabled: true

RSpec/Eq:
  Enabled: true

RSpec/IndexedLet:
  Enabled: false

RSpec/MatchArray:
  Enabled: true

RSpec/MetadataStyle:
  Enabled: true

RSpec/ReceiveMessages:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/Rails/NegationBeValid:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/ClickLinkOrButtonStyle:
  Enabled: true

Capybara/RSpec/HaveSelector:
  Enabled: true

Capybara/RSpec/PredicateMatcher:
  Enabled: true

FactoryBot/ConsistentParenthesesStyle:
  Enabled: true

FactoryBot/SyntaxMethods:
  Enabled: true

FactoryBot/FactoryNameStyle:
  Enabled: true

FactoryBot/AssociationStyle:
  Enabled: true

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true

FactoryBot/IdSequence:
  Enabled: true

FactoryBot/RedundantFactoryOption:
  Enabled: true
