development: &default
  database1:
    adapter: sqlite3
    database: db/dev_database1.sqlite3
  database2:
    adapter: sqlite3
    database: db/dev_database2.sqlite3

test:
  database1:
    adapter: sqlite3
    database: db/test_database1.sqlite3
  database2:
    adapter: sqlite3
    database: db/test_database2.sqlite3

production:
  database1:
    adapter: sqlite3
    database: db/prod_database1.sqlite3
    pool: 5
    timeout: 5000
  database2:
    adapter: sqlite3
    database: db/prod_database2.sqlite3
    pool: 5
    timeout: 5000
